Repository Netvent/storyly-sdk, pull requests merged in 2023-08, with the labels that each got.

#295 feat(storyly-react-native): add share config
  react-native/storyly-react-native/RNStoryly.js
  react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt
  react-native/storyly-react-native/ios/RCTConvert+Storyly.swift
Labels: feat

#296 build(storyly-flutter): release 2.0.1
  flutter/storyly_flutter/CHANGELOG.md
  flutter/storyly_flutter/pubspec.lock
  flutter/storyly_flutter/pubspec.yaml
  react-native/storyly-react-native/RELEASENOTES.md
  react-native/storyly-react-native/package.json
Labels: build

#297 feat: add demo expo app
  react-native/StorylyDemoExpo/.gitignore
  react-native/StorylyDemoExpo/App.tsx
  react-native/StorylyDemoExpo/README.md
  react-native/StorylyDemoExpo/app.json
  react-native/StorylyDemoExpo/assets/adaptive-icon.png
  react-native/StorylyDemoExpo/assets/favicon.png
  react-native/StorylyDemoExpo/assets/icon.png
  react-native/StorylyDemoExpo/assets/splash.png
  react-native/StorylyDemoExpo/babel.config.js
  react-native/StorylyDemoExpo/eas.json
  react-native/StorylyDemoExpo/package-lock.json
  react-native/StorylyDemoExpo/package.json
  react-native/StorylyDemoExpo/tsconfig.json
Labels: react native, feat, docs

#299 build(storyly-flutter): release 2.1.0
  flutter/storyly_flutter/CHANGELOG.md
  flutter/storyly_flutter/android/build.gradle
  flutter/storyly_flutter/example/ios/Podfile.lock
  flutter/storyly_flutter/example/pubspec.lock
  flutter/storyly_flutter/ios/storyly_flutter.podspec
  flutter/storyly_flutter/pubspec.yaml
Labels: build

#301 feat(storyly-react-native): add product callbacks and cart sync
  react-native/storyly-react-native/RNStoryly.js
  react-native/storyly-react-native/android/build.gradle
  react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyDataConverter.kt
  react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyManager.kt
  react-native/storyly-react-native/android/src/main/java/com/appsamurai/storyly/reactnative/STStorylyView.kt
  react-native/storyly-react-native/index.d.ts
  react-native/storyly-react-native/ios/RCTConvert+Storyly.swift
  react-native/storyly-react-native/ios/STStorylyDataConverter.swift
  react-native/storyly-react-native/ios/STStorylyManager.m
  react-native/storyly-react-native/ios/STStorylyManager.swift
  react-native/storyly-react-native/ios/STStorylyView.swift
  react-native/storyly-react-native/storyly-react-native.podspec
Labels: feat

#306 feat(str-flutter): add cart sync and product callbacks
  flutter/storyly_flutter/android/build.gradle
  flutter/storyly_flutter/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/FlutterStorylyView.kt
  flutter/storyly_flutter/ios/Classes/FlutterStorylyViewWrapper.swift
  flutter/storyly_flutter/ios/storyly_flutter.podspec
  flutter/storyly_flutter/lib/storyly_flutter.dart
Labels: feat

#307 build(storyly-react-native): release 2.2.0
  flutter/storyly_flutter/example/ios/Podfile.lock
  react-native/storyly-react-native/RELEASENOTES.md
  react-native/storyly-react-native/StorylyDemo/ios/Podfile.lock
  react-native/storyly-react-native/package.json
Labels: build

#308 build(storyly-flutter): release 2.2.0
  flutter/storyly_flutter/CHANGELOG.md
  flutter/storyly_flutter/ios/storyly_flutter.podspec
  flutter/storyly_flutter/lib/storyly_flutter.dart
  flutter/storyly_flutter/pubspec.yaml
Labels: build
